import { permissionHasCapability, resolvePublicSitePermission } from './api/_lib/publicSiteAuth.js'
import { getBoundDb } from './api/_lib/database.js'
import { upsertNativeEntry, saveRevisionSnapshot, slugify } from './api/_lib/nativePublicContent.js'
import { upsertMediaAsset } from './api/_lib/mediaAssets.js'
import { validateMediaBytes } from './api/_lib/mediaSignature.js'

const MAX_SHARE_FILE_BYTES=250*1024*1024
const BINDINGS=['colophon_MEDIA_BUCKET','MEDIA_BUCKET','ASSETS_BUCKET','colophon_AUDIO_BUCKET','AUDIO_MEDIA_BUCKET']
export async function onRequestGet(context){return Response.redirect(new URL('/#/share-target',context.request.url).toString(),302)}
export async function onRequestPost(context){const permission=await resolvePublicSitePermission(context);if(!permissionHasCapability(permission,'content:write')&&!permission.canEdit)return text('Authentication required before sharing into Colophon.',403);const db=getBoundDb(context);if(!db)return text('Publishing database is unavailable.',503);try{const form=await context.request.formData();const title=clean(form.get('title'),220),textBody=clean(form.get('text'),20000),sourceUrl=safeUrl(form.get('url')||extractUrl(textBody));const media=[];for(const value of form.getAll('media').concat(form.getAll('files'))){if(!value||typeof value.arrayBuffer!=='function')continue;if(Number(value.size||0)>MAX_SHARE_FILE_BYTES)throw Object.assign(new Error('Shared file is too large.'),{status:413});const mime=String(value.type||'application/octet-stream').toLowerCase();const bytes=await value.arrayBuffer();const validation=validateMediaBytes(bytes,mime);if(!validation.ok)throw Object.assign(new Error(validation.reason||'Shared file type did not match its contents.'),{status:415});const bucketInfo=findBucket(context.env);if(!bucketInfo)throw Object.assign(new Error('Media storage is not configured.'),{status:503});const id=`media-${crypto.randomUUID()}`,filename=safeFilename(value.name||'shared-file'),key=`media/uploads/shared/${id}-${filename}`;await bucketInfo.bucket.put(key,bytes,{httpMetadata:{contentType:mime},customMetadata:{source:'web-share-target',filename}});const publicUrl=new URL('/api/media/files',context.request.url);publicUrl.searchParams.set('key',key);publicUrl.searchParams.set('filename',filename);const asset=await upsertMediaAsset(db,{id,title:filename.replace(/\.[^.]+$/,''),url:publicUrl.toString(),downloadUrl:publicUrl.toString(),mimeType:mime,size:Number(value.size||0),mediaType:mediaType(mime),filename,folder:'Shared',storageKey:key,source:'web-share-target'});media.push(asset)}const now=new Date().toISOString();const entry=await upsertNativeEntry(db,{id:`native-${crypto.randomUUID()}`,contentType:'note',status:'draft',workflowState:'draft',target:'general',title:title||sourceUrl||'Shared draft',slug:slugify(title||`shared-${Date.now()}`),excerpt:textBody.slice(0,600),body:textBody,bodyHtml:buildBody(textBody,sourceUrl,media),sourceType:'web-share-target',sourceKind:'web-share-target',sourceLabel:'Shared to Colophon',sourceUrl,sourceNotes:'Captured through the authenticated Web Share Target and left unpublished for editorial review.',relatedAssets:media.map(a=>({id:a.id,role:'shared',type:a.mediaType,url:a.url,mimeType:a.mimeType,size:a.size})),createdAt:now,updatedAt:now});await saveRevisionSnapshot(db,entry,'web-share-target');return Response.redirect(new URL(`/wp-admin/native-bridge?edit=${encodeURIComponent(entry.id)}&shared=1`,context.request.url).toString(),303)}catch(e){return text(String(e.message||e),Number(e.status||400))}}
function findBucket(env={}){for(const name of BINDINGS)if(env[name])return{name,bucket:env[name]};return null}function clean(v,n){return String(v||'').trim().slice(0,n)}function safeUrl(v){try{const u=new URL(String(v||''));return ['http:','https:'].includes(u.protocol)?u.toString():''}catch{return''}}function extractUrl(v){return String(v||'').match(/https?:\/\/[^\s<>]+/i)?.[0]||''}function safeFilename(v){return String(v||'file').split(/[\\/]/).pop().replace(/[^a-z0-9._-]+/gi,'-').slice(0,180)||'file'}function mediaType(m){if(m.startsWith('image/'))return'image';if(m.startsWith('audio/'))return'audio';if(m.startsWith('video/'))return'video';if(m==='application/pdf')return'pdf';return'file'}function esc(v){return String(v||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}function buildBody(text,source,media){const parts=[];if(text)parts.push(`<p>${esc(text).replace(/\n/g,'<br>')}</p>`);if(source)parts.push(`<p>Source: <a href="${esc(source)}">${esc(source)}</a></p>`);for(const a of media){if(a.mediaType==='image')parts.push(`<p><img src="${esc(a.url)}" alt=""></p>`);else parts.push(`<p><a href="${esc(a.url)}">${esc(a.filename||a.title||'Shared file')}</a></p>`)}return parts.join('\n')}function text(v,s=200){return new Response(v,{status:s,headers:{'content-type':'text/plain; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}})}
