import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'
import { courseProgressSummary, lessonSequence, lessonUnlocked, normalizeCourse, publicCourse } from '../shared/courseModel.js'
import { emptyCourseProgress, exportCourseProgress, importCourseProgress } from '../src/lib/courseProgress.js'

test('course model orders lessons and honors prerequisites',()=>{const c=normalizeCourse({title:'Demo',status:'published',sections:[{id:'s',title:'S',lessons:[{id:'b',title:'B',order:2,prerequisites:['a']},{id:'a',title:'A',order:1}]}]});assert.deepEqual(lessonSequence(c).map(l=>l.id),['a','b']);assert.equal(lessonUnlocked(c,'b',[]),false);assert.equal(lessonUnlocked(c,'b',['a']),true)})
test('public course snapshot strips editorial workflow fields',()=>{const c=publicCourse({title:'Demo',status:'published',contributors:['Private'],reviewers:['Editor'],reviewNotes:'internal',sections:[]});assert.equal(c.reviewNotes,undefined);assert.equal(c.contributors,undefined);assert.equal(c.reviewers,undefined)})
test('progress summary is deterministic',()=>{const c=normalizeCourse({title:'D',sections:[{lessons:[{id:'a'},{id:'b'}]}]});assert.deepEqual(courseProgressSummary(c,{completedLessons:['a']}),{total:2,completed:1,percent:50})})
test('courses are optional and routed in public and admin surfaces',()=>{const modules=fs.readFileSync(new URL('../src/lib/publishingModules.js',import.meta.url),'utf8');const routes=fs.readFileSync(new URL('../src/routing/routes.js',import.meta.url),'utf8');const app=fs.readFileSync(new URL('../src/App.jsx',import.meta.url),'utf8');assert.match(modules,/id: 'courses'/);assert.match(routes,/course: '\/courses\/:slug'/);assert.match(routes,/courses: '\/wp-admin\/courses'/);assert.match(app,/CourseReaderPage/);assert.match(app,/CoursesAdminPage/)})
test('course store uses published snapshots and revision conflict checks',()=>{const source=fs.readFileSync(new URL('../functions/api/_lib/courseStore.js',import.meta.url),'utf8');assert.match(source,/course_publications/);assert.match(source,/course_revisions/);assert.match(source,/Reload before saving/);assert.match(source,/publishedVersion/)})

test('course progress export/import validates version, course and lesson ids',()=>{const course=normalizeCourse({slug:'demo',title:'Demo',sections:[{lessons:[{id:'a'},{id:'b'}]}]});const progress={...emptyCourseProgress(course.slug),completedLessons:['a','ghost'],bookmarks:['b','ghost'],notes:{a:'note',ghost:'drop'}};const text=exportCourseProgress(progress);const restored=importCourseProgress(text,course);assert.deepEqual(restored.completedLessons,['a']);assert.deepEqual(restored.bookmarks,['b']);assert.deepEqual(restored.notes,{a:'note'});assert.throws(()=>importCourseProgress(JSON.stringify({...progress,version:999}),course),/Unsupported/);assert.throws(()=>importCourseProgress(JSON.stringify({...progress,courseSlug:'other'}),course),/different course/)})
test('activities completion rules are enforced by the reader UI',()=>{const source=fs.readFileSync(new URL('../src/components/CoursePages.jsx',import.meta.url),'utf8');assert.match(source,/completionRule!=='activities'/);assert.match(source,/Complete required activities first/)})
