import { getBoundDb } from './_lib/database.js'
import { permissionHasCapability, resolvePublicSitePermission } from './_lib/publicSiteAuth.js'
import { deleteCourse, getCourse, listCourses, saveCourse } from './_lib/courseStore.js'
import { inferActorFromRequest, writeAuditLog } from './_lib/auditLog.js'
export async function onRequestGet(context){ const db=getBoundDb(context); if(!db)return json({ok:false,error:'course storage unavailable'},503); const url=new URL(context.request.url); const permission=await resolvePublicSitePermission(context); const editor=url.searchParams.get('editor')==='1'; if(editor&&!permission.canAccessAdmin)return json({ok:false,error:'authentication required'},403); try{ const key=url.searchParams.get('id')||url.searchParams.get('slug'); if(key){const item=await getCourse(db,key,{editor});return item?json({ok:true,item}):json({ok:false,error:'course not found'},404)} const items=await listCourses(db,{publicOnly:!editor}); return json({ok:true,items}) }catch(e){return json({ok:false,error:String(e.message||e)},500)} }
export async function onRequestPost(context){ return write(context) }
export async function onRequestPut(context){ return write(context) }
export async function onRequestDelete(context){ const permission=await resolvePublicSitePermission(context); if(!permissionHasCapability(permission,'publishing:write'))return json({ok:false,error:'publishing permission required'},403); const db=getBoundDb(context); if(!db)return json({ok:false,error:'course storage unavailable'},503); const body=await context.request.json().catch(()=>({})); if(!body.id)return json({ok:false,error:'id is required'},400); await deleteCourse(db,String(body.id)); return json({ok:true,removed:true}) }
async function write(context){ const permission=await resolvePublicSitePermission(context); if(!permissionHasCapability(permission,'publishing:write'))return json({ok:false,error:'publishing permission required'},403); const db=getBoundDb(context); if(!db)return json({ok:false,error:'course storage unavailable'},503); try{ const body=await context.request.json(); const item=await saveCourse(db,body.item||body,permission.actor||'editor'); await writeAuditLog(db,{action:'courses.save',entityType:'course',entityId:item.id,actor:inferActorFromRequest(context.request),detail:{slug:item.slug,status:item.status,revision:item.revision}}).catch(()=>{}); return json({ok:true,item}) }catch(e){return json({ok:false,error:String(e.message||e)},Number(e.status||400))} }
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}})}
