import { useEffect, useMemo, useState } from 'react'
import { createContributor, deleteCorrespondenceMessage, loadCorrespondence, patchCorrespondence, sendMessage, uploadCampaignArchiveMedia } from '../lib/campaignCorrespondenceApi'

export function CampaignCorrespondenceAdmin({ campaign, enabled = true, onNotice }) {
  const [data, setData] = useState(null)
  const [person, setPerson] = useState({ displayName: '', byline: '', pin: '', directPublish: true })
  const [createdLink, setCreatedLink] = useState('')
  const [message, setMessage] = useState('')
  const [recipientId, setRecipientId] = useState('')
  const [instagram, setInstagram] = useState({ caption: '', url: '', publishedAt: '', file: null })
  const [busy, setBusy] = useState('')
  const [editingMessage, setEditingMessage] = useState(null)
  const [instagramAuth, setInstagramAuth] = useState({ status: null, link: '' })
  const activeContributors = useMemo(() => (data?.contributors || []).filter((item) => !item.revokedAt), [data])

  async function reload() { try { setData(await loadCorrespondence(campaign.slug, '', true)) } catch (error) { onNotice(`Correspondence failed to load: ${error.message}`, 'error') } }
  useEffect(() => { if (enabled) reload() }, [campaign.id, enabled])
  useEffect(() => {
    if (activeContributors.length === 1) setRecipientId(activeContributors[0].id)
    else if (!activeContributors.some((item) => item.id === recipientId)) setRecipientId('')
  }, [activeContributors, recipientId])

  async function add(event) {
    event.preventDefault()
    try {
      const result = await createContributor(campaign.slug, person)
      setCreatedLink(`${window.location.origin}/contribute/${campaign.slug}#access=${result.token}`)
      setPerson({ displayName: '', byline: '', pin: '', directPublish: true })
      await reload(); onNotice('Contributor key created. Copy it now; the secret is not shown again.', 'success')
    } catch (error) { onNotice(error.message, 'error') }
  }
  async function revoke(item) { if (!window.confirm(`${item.revokedAt ? 'Restore' : 'Revoke'} access for ${item.displayName}?`)) return; await patchCorrespondence({ action: 'revoke', id: item.id, revoked: !item.revokedAt }); await reload() }
  async function reissue(item) { if (!window.confirm(`Replace the private link for ${item.displayName}? Their old link and signed-in sessions will stop working. Their PIN and message history stay the same.`)) return; setBusy(`reissue-${item.id}`); try { const result = await patchCorrespondence({ action: 'reissue', id: item.id }); setCreatedLink(`${window.location.origin}/contribute/${campaign.slug}#access=${result.token}`); await reload(); onNotice(`New private link created for ${item.displayName}. Their PIN is unchanged.`, 'success') } catch (error) { onNotice(error.message, 'error') } finally { setBusy('') } }

  async function send(event) {
    event.preventDefault()
    if (!message.trim()) return
    if (!recipientId) { onNotice(activeContributors.length ? 'Choose which contributor should receive this private message.' : 'Create or restore an active contributor before sending a private message.', 'error'); return }
    try { await sendMessage(campaign.slug, { body: message, visibility: 'private', recipientContributorId: recipientId }); setMessage(''); await reload(); onNotice('Private message sent to the selected contributor.', 'success') }
    catch (error) { onNotice(error.message, 'error') }
  }

  async function assignRecipient(item, contributorId) {
    if (!contributorId) return
    setBusy(`recipient-${item.id}`)
    try { await patchCorrespondence({ action: 'recipient', id: item.id, recipientContributorId: contributorId }); await reload(); onNotice('Private-message recipient assigned.', 'success') }
    catch (error) { onNotice(error.message, 'error') } finally { setBusy('') }
  }

  async function importInstagram(event) { event.preventDefault(); setBusy('import'); try { const media = await uploadCampaignArchiveMedia(instagram.file); await sendMessage(campaign.slug, { body: instagram.caption, ...media, visibility: 'public', originSource: 'instagram', originId: instagramId(instagram.url), originUrl: instagram.url, originalPublishedAt: instagram.publishedAt || undefined }); setInstagram({ caption: '', url: '', publishedAt: '', file: null }); event.currentTarget.reset(); await reload(); onNotice('Social post archived and published.', 'success') } catch (error) { onNotice(error.message, 'error') } finally { setBusy('') } }
  async function syncInstagram() { setBusy('sync'); try { const response = await fetch('/api/campaign-instagram-sync', { method: 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ campaign: campaign.slug }) }); const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.error || 'sync failed'); await reload(); onNotice(`Account scan checked ${result.examined || 0} posts: ${result.imported} imported, ${result.skipped} already archived, ${result.filtered || 0} outside the configured campaign filters.${result.errors?.length ? ` ${result.errors.length} media download errors.` : ''}`, 'success') } catch (error) { onNotice(error.message, 'error') } finally { setBusy('') } }
  async function instagramAction(action) { setBusy(`instagram-${action}`); try { const response = await fetch('/api/campaign-instagram-auth', { method: 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action, campaign: campaign.slug }) }); const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.error || 'Instagram authorization failed'); if (action === 'invite') { const link = `${window.location.origin}/campaigns/${campaign.slug}/instagram-connect#access=${result.token}`; setInstagramAuth((value) => ({ ...value, link })); await navigator.clipboard?.writeText(link); onNotice('One-use Instagram authorization link created and copied.', 'success') } else if (action === 'status') setInstagramAuth((value) => ({ ...value, status: result.status })) } catch (error) { onNotice(error.message, 'error') } finally { setBusy('') } }
  async function setQuestionStatus(item, status) { await patchCorrespondence({ action: 'question', id: item.id, status, editorNote: item.editorNote || '', messageId: item.messageId || '' }); await reload() }
  async function saveMessage(event) { event.preventDefault(); if (!editingMessage?.body.trim()) return; setBusy(`edit-${editingMessage.id}`); try { await patchCorrespondence({ action: 'message', id: editingMessage.id, body: editingMessage.body, visibility: editingMessage.visibility }); setEditingMessage(null); await reload(); onNotice('Correspondence message updated.', 'success') } catch (error) { onNotice(error.message, 'error') } finally { setBusy('') } }
  async function removeMessage(item) { const preview = item.body ? `“${item.body.slice(0, 70)}${item.body.length > 70 ? '…' : ''}”` : 'this attachment'; if (!window.confirm(`Permanently delete ${preview}? This removes it from the private room and any public dispatch feed.`)) return; setBusy(`delete-${item.id}`); try { await deleteCorrespondenceMessage(item.id); if (editingMessage?.id === item.id) setEditingMessage(null); await reload(); onNotice('Correspondence message deleted.', 'success') } catch (error) { onNotice(error.message, 'error') } finally { setBusy('') } }

  if (!enabled) return <section className="wp-meta-box campaign-correspondence-admin campaign-correspondence-admin--disabled"><div className="campaign-admin-section-header"><div><h2>Campaign Correspondence</h2><p className="description">This module is off. Enable campaign correspondence above, save the campaign, then create contributor access here.</p></div><span className="description">Disabled</span></div></section>

  return <section className="wp-meta-box campaign-correspondence-admin">
    <div className="campaign-admin-section-header"><div><h2>Campaign Correspondence</h2><p className="description">Private contributor conversations, public dispatches, social continuity, contributor keys, and moderated questions.</p></div><span className="description">{data?.messages?.length || 0} messages · {data?.questions?.filter((q) => q.status === 'new').length || 0} new</span></div>

    <div className="campaign-instagram-auth"><h3>Connect Instagram for preservation</h3><p className="description">Create a one-use authorization link for the account owner. The connection is scoped to this campaign and does not require sharing a password.</p><p><button className="button button--primary" type="button" disabled={Boolean(busy)} onClick={() => instagramAction('invite')}>{busy === 'instagram-invite' ? 'Creating…' : 'Create authorization link'}</button> <button className="button" type="button" disabled={Boolean(busy)} onClick={() => instagramAction('status')}>Check connection</button></p>{instagramAuth.link ? <div className="notice notice-success"><strong>Send this one-use link to the account owner</strong><input readOnly value={instagramAuth.link} onFocus={(event) => event.target.select()} /><button className="button" type="button" onClick={() => navigator.clipboard?.writeText(instagramAuth.link)}>Copy</button><p>It expires in seven days and only authorizes this campaign.</p></div> : null}{instagramAuth.status ? <p className="description">{instagramAuth.status.connected ? `Connected to @${instagramAuth.status.username || 'Instagram account'}` : 'Not connected.'}</p> : null}</div>

    <div className="campaign-instagram-import"><div><h3>Social continuity archive</h3><p className="description"><strong>Connected does not mean continuously scheduled.</strong> Scan the connected account after publishing a campaign post, or archive a specific post manually below.</p><p className="description">Native repost-only items may not be returned by platform APIs. Use the manual archive when an item is not available through the connected media feed.</p><a className="button" href={`/contribute/${campaign.slug}?preview=1`} target="_blank" rel="noreferrer">Preview contributor portal ↗</a> <button className="button button--primary" type="button" disabled={Boolean(busy)} onClick={syncInstagram}>{busy === 'sync' ? 'Scanning…' : 'Scan connected account now'}</button></div><form onSubmit={importInstagram}><label>Original post URL<input type="url" required placeholder="https://www.instagram.com/p/…" value={instagram.url} onChange={(e) => setInstagram({ ...instagram, url: e.target.value })} /></label><label>Original date<input type="datetime-local" value={instagram.publishedAt} onChange={(e) => setInstagram({ ...instagram, publishedAt: e.target.value })} /></label><label>Caption<textarea rows="5" value={instagram.caption} onChange={(e) => setInstagram({ ...instagram, caption: e.target.value })} /></label><label>Screenshot or saved video<input type="file" required accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm" onChange={(e) => setInstagram({ ...instagram, file: e.target.files?.[0] || null })} /></label><button className="button button--primary" disabled={Boolean(busy)}>{busy === 'import' ? 'Archiving…' : 'Archive and publish'}</button></form></div>

    <div className="campaign-correspondence-admin__grid"><div><h3>Contributor access</h3><form onSubmit={add} className="campaign-contributor-create"><input required placeholder="Display name" value={person.displayName} onChange={(e) => setPerson({ ...person, displayName: e.target.value })} /><input placeholder="Public byline (optional)" value={person.byline} onChange={(e) => setPerson({ ...person, byline: e.target.value })} /><input required inputMode="numeric" pattern="[0-9]{4,8}" placeholder="4–8 digit PIN" value={person.pin} onChange={(e) => setPerson({ ...person, pin: e.target.value })} /><label><input type="checkbox" checked={person.directPublish} onChange={(e) => setPerson({ ...person, directPublish: e.target.checked })} /> Can publish directly</label><button className="button button--primary">Create private link</button></form>{createdLink ? <div className="notice notice-success"><strong>Save this private link</strong><input readOnly value={createdLink} onFocus={(e) => e.target.select()} /><button type="button" className="button" onClick={() => navigator.clipboard?.writeText(createdLink)}>Copy</button><p>Bookmark it or send it now. If it is lost, replace the link below. The PIN and message history stay the same.</p></div> : null}<div className="campaign-admin-simple-list">{data?.contributors?.map((item) => <article key={item.id}><div><strong>{item.displayName}</strong><small>{item.byline} · {item.permissions.directPublish ? 'direct publisher' : 'review only'}{item.revokedAt ? ' · revoked' : ''}</small></div><div className="campaign-contributor-actions"><button className="button" type="button" disabled={Boolean(busy)} onClick={() => reissue(item)}>{busy === `reissue-${item.id}` ? 'Replacing…' : 'Replace private link'}</button><button className="button" type="button" onClick={() => revoke(item)}>{item.revokedAt ? 'Restore' : 'Revoke'}</button></div></article>)}</div></div>

      <div><h3>Private room</h3><div className="campaign-admin-thread">{data?.messages?.map((item) => <article key={item.id} className={`is-${item.senderRole}`}>{editingMessage?.id === item.id ? <form className="campaign-admin-message-edit" onSubmit={saveMessage}><label>Message<textarea rows="4" autoFocus value={editingMessage.body} onChange={(e) => setEditingMessage({ ...editingMessage, body: e.target.value })} /></label><label>Visibility<select value={editingMessage.visibility} onChange={(e) => setEditingMessage({ ...editingMessage, visibility: e.target.value })}><option value="private">Private</option><option value="public">Public dispatch</option></select></label><div><button className="button button--primary" disabled={busy === `edit-${item.id}`}>{busy === `edit-${item.id}` ? 'Saving…' : 'Save changes'}</button><button className="button" type="button" onClick={() => setEditingMessage(null)}>Cancel</button></div></form> : <><strong>{item.displayName}</strong><p>{item.body || `[${item.mediaType} attachment]`}</p><small>{new Date(item.createdAt).toLocaleString()} · {messageDestination(item)}</small>{item.recipientRequired ? <RecipientRepair item={item} contributors={activeContributors} busy={busy === `recipient-${item.id}`} onAssign={assignRecipient} /> : null}<div className="campaign-admin-message-actions"><button className="button button-small" type="button" onClick={() => setEditingMessage({ id: item.id, body: item.body || '', visibility: item.visibility })}>Edit</button><button className="button button-small button-link-delete" type="button" disabled={busy === `delete-${item.id}`} onClick={() => removeMessage(item)}>{busy === `delete-${item.id}` ? 'Deleting…' : 'Delete'}</button></div></>}</article>)}</div>
        <form onSubmit={send} className="campaign-admin-message"><label className="native-content-editor__field"><span>Send privately to</span><select value={recipientId} disabled={!activeContributors.length} onChange={(event) => setRecipientId(event.target.value)}><option value="">{activeContributors.length ? 'Choose contributor…' : 'No active contributors'}</option>{activeContributors.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><textarea rows="3" placeholder="Private follow-up…" value={message} onChange={(e) => setMessage(e.target.value)} /><p className="description">Only the selected contributor and publication editors can see this message.</p><button className="button button--primary" disabled={!recipientId || !activeContributors.length}>Send private message</button></form></div></div>

    <div><h3>Public question queue</h3>{data?.questions?.length ? <div className="campaign-question-queue">{data.questions.map((item) => <article key={item.id}><div><span>{item.status}</span><strong>{item.submitterName}</strong><p>{item.question}</p></div><select value={item.status} onChange={(e) => setQuestionStatus(item, e.target.value)}>{['new','shortlisted','sent','answered','ready','published','archived'].map((status) => <option key={status}>{status}</option>)}</select></article>)}</div> : <p className="description">No public questions yet.</p>}</div>
  </section>
}

function RecipientRepair({ item, contributors, busy, onAssign }) { const [value, setValue] = useState(''); return <div className="notice notice-warning"><strong>Recipient required</strong><p>This legacy private editor message is hidden from contributors until a recipient is assigned.</p><select value={value} onChange={(event) => setValue(event.target.value)}><option value="">Choose contributor…</option>{contributors.map((person) => <option key={person.id} value={person.id}>{person.displayName}</option>)}</select> <button className="button" type="button" disabled={!value || busy} onClick={() => onAssign(item, value)}>{busy ? 'Assigning…' : 'Assign recipient'}</button></div> }
function messageDestination(item) { if (item.visibility === 'public') return 'PUBLIC · campaign website'; if (item.recipientContributorNames?.length) return `PRIVATE · to ${item.recipientContributorNames.join(', ')}`; if (item.senderRole === 'contributor') return 'PRIVATE · contributor to editors'; return 'PRIVATE · recipient required' }
function instagramId(url) { return String(url || '').replace(/[?#].*$/, '').replace(/\/$/, '').split('/').pop() || String(url || '') }
