export const THEME_FORMAT = 'colophon-theme'
export const THEME_FORMAT_VERSION = 1
export const MAX_THEME_CSS_BYTES = 250_000
export const MAX_THEME_ASSET_BYTES = 2_000_000
export const MAX_THEME_TOTAL_ASSET_BYTES = 8_000_000
const SAFE_ID = /^[a-z0-9][a-z0-9-]{0,63}$/; const SAFE_VERSION = /^[0-9A-Za-z][0-9A-Za-z.+_-]{0,63}$/; const SAFE_ASSET_PATH = /^assets\/[A-Za-z0-9][A-Za-z0-9._/-]{0,180}$/; const SAFE_ASSET_MIME = /^(image\/(?:png|jpeg|gif|webp|svg\+xml)|font\/(?:woff|woff2))$/
export const BUILTIN_NEUTRAL_THEME = Object.freeze({ format: THEME_FORMAT, formatVersion: THEME_FORMAT_VERSION, id: 'neutral', name: 'Neutral', version: '1.0.0', author: 'Colophon contributors', description: 'The neutral built-in Colophon publication theme.', colophon: '>=0.1.0', css: '', tokens: {}, layout: { header: 'default', footer: 'default', article: 'default', archive: 'grid' }, assets: [], builtIn: true })
function cleanText(value, max = 240) { return String(value || '').replace(/[\u0000-\u001f\u007f]/g, ' ').trim().slice(0, max) }
function safeCss(css = '') { const value = String(css || ''); if (new TextEncoder().encode(value).length > MAX_THEME_CSS_BYTES) throw new Error('theme CSS is too large'); if (/@import\b/i.test(value)) throw new Error('@import is not allowed in theme CSS'); if (/(?:expression\s*\(|javascript\s*:|-moz-binding\s*:|behavior\s*:)/i.test(value)) throw new Error('unsafe CSS construct'); if (/url\s*\(/i.test(value)) throw new Error('literal url() is not allowed; use theme-asset("assets/...")'); return value }
function normalizeTokens(input) { const out = {}; if (!input || typeof input !== 'object' || Array.isArray(input)) return out; for (const [key, value] of Object.entries(input).slice(0, 80)) { if (!/^--[a-z0-9-]{1,80}$/i.test(key)) continue; const clean = cleanText(value, 160); if (!clean || /[;{}]/.test(clean)) continue; out[key] = clean } return out }
function normalizeLayout(input) { const raw = input && typeof input === 'object' && !Array.isArray(input) ? input : {}; return { header: ['default', 'compact', 'centered'].includes(raw.header) ? raw.header : 'default', footer: ['default', 'compact', 'columns'].includes(raw.footer) ? raw.footer : 'default', article: ['default', 'wide', 'narrow'].includes(raw.article) ? raw.article : 'default', archive: ['grid', 'list', 'stack'].includes(raw.archive) ? raw.archive : 'grid' } }
function decodeBase64Length(value = '') { const clean = String(value || '').replace(/\s+/g, ''); if (!/^[A-Za-z0-9+/]*={0,2}$/.test(clean)) return -1; return Math.floor(clean.length * 3 / 4) - (clean.endsWith('==') ? 2 : clean.endsWith('=') ? 1 : 0) }
function normalizeAssets(input) { if (!Array.isArray(input)) return []; const seen = new Set(); const assets = []; let total = 0; for (const raw of input.slice(0, 64)) { if (!raw || typeof raw !== 'object') continue; const path = cleanText(raw.path, 200); const mime = cleanText(raw.mime, 100).toLowerCase(); const dataBase64 = String(raw.dataBase64 || '').replace(/\s+/g, ''); if (!SAFE_ASSET_PATH.test(path) || path.includes('..') || path.startsWith('/') || seen.has(path)) throw new Error(`unsafe theme asset path: ${path || '(empty)'}`); if (!SAFE_ASSET_MIME.test(mime)) throw new Error(`unsupported theme asset type: ${mime || '(empty)'}`); const bytes = decodeBase64Length(dataBase64); if (bytes < 0 || bytes > MAX_THEME_ASSET_BYTES) throw new Error(`theme asset invalid or too large: ${path}`); total += bytes; if (total > MAX_THEME_TOTAL_ASSET_BYTES) throw new Error('theme package assets are too large'); seen.add(path); assets.push({ path, mime, dataBase64 }) } return assets }
export function normalizeThemeManifest(input, { allowBuiltIn = false } = {}) { if (!input || typeof input !== 'object' || Array.isArray(input)) throw new Error('theme manifest must be an object'); const id = cleanText(input.id, 64).toLowerCase(); const version = cleanText(input.version, 64); if (!SAFE_ID.test(id)) throw new Error('theme id must use lowercase letters, numbers, and hyphens'); if (!SAFE_VERSION.test(version)) throw new Error('theme version is invalid'); const format = cleanText(input.format || THEME_FORMAT, 40); const formatVersion = Number(input.formatVersion || THEME_FORMAT_VERSION); if (format !== THEME_FORMAT || formatVersion !== THEME_FORMAT_VERSION) throw new Error('unsupported Colophon theme format'); return { format: THEME_FORMAT, formatVersion: THEME_FORMAT_VERSION, id, name: cleanText(input.name || id, 120), version, author: cleanText(input.author, 160), description: cleanText(input.description, 500), colophon: cleanText(input.colophon || '>=0.1.0', 80), css: safeCss(input.css || ''), tokens: normalizeTokens(input.tokens), layout: normalizeLayout(input.layout), assets: normalizeAssets(input.assets), builtIn: allowBuiltIn && input.builtIn === true } }
export function normalizeThemeState(input = {}) { const raw = input && typeof input === 'object' && !Array.isArray(input) ? input : {}; const installed = [BUILTIN_NEUTRAL_THEME]; const seen = new Set(['neutral']); for (const item of Array.isArray(raw.installed) ? raw.installed : []) { try { const theme = normalizeThemeManifest(item); if (seen.has(theme.id)) continue; seen.add(theme.id); installed.push(theme) } catch {} } const requested = String(raw.activeId || 'neutral').trim().toLowerCase(); return { activeId: installed.some((theme) => theme.id === requested) ? requested : 'neutral', installed } }
export function installTheme(state, input) { const theme = normalizeThemeManifest(input); if (theme.id === 'neutral') throw new Error('the built-in neutral theme cannot be replaced'); const normalized = normalizeThemeState(state); const installed = normalized.installed.filter((item) => item.id !== theme.id); installed.push(theme); return { activeId: normalized.activeId, installed } }
export function removeTheme(state, themeId) { const normalized = normalizeThemeState(state); const id = String(themeId || '').trim().toLowerCase(); if (!id || id === 'neutral') throw new Error('the built-in theme cannot be removed'); if (normalized.activeId === id) throw new Error('activate another theme before removing this one'); return { ...normalized, installed: normalized.installed.filter((theme) => theme.id !== id) } }
export function activateTheme(state, themeId) { const normalized = normalizeThemeState(state); const id = String(themeId || '').trim().toLowerCase(); if (!normalized.installed.some((theme) => theme.id === id)) throw new Error('theme is not installed'); return { ...normalized, activeId: id } }
export function activeTheme(state) { const normalized = normalizeThemeState(state); return normalized.installed.find((theme) => theme.id === normalized.activeId) || BUILTIN_NEUTRAL_THEME }
export function materializeThemeCss(themeInput) { const theme = themeInput?.builtIn ? themeInput : normalizeThemeManifest(themeInput); const assets = new Map((theme.assets || []).map((asset) => [asset.path, asset])); return String(theme.css || '').replace(/theme-asset\(\s*["'](assets\/[^"']+)["']\s*\)/g, (_, path) => { const asset = assets.get(path); return asset ? `url("data:${asset.mime};base64,${asset.dataBase64}")` : 'none' }) }
export function themePackageJson(themeInput) { const theme = themeInput?.builtIn ? { ...themeInput, builtIn: false } : normalizeThemeManifest(themeInput); return JSON.stringify(theme, null, 2) }
