const STATUSES = ['pending_email','awaiting_moderation','approved','rejected','spam','revoked']
const VERIFY_TTL = 72*60*60*1000
export async function ensureSignatureTables(db){
  for(const sql of [
    `CREATE TABLE IF NOT EXISTS campaign_signature_forms (campaign_id TEXT PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 0, title TEXT NOT NULL DEFAULT 'Sign', intro TEXT NOT NULL DEFAULT '', config_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS campaign_signatures (id TEXT PRIMARY KEY, campaign_id TEXT NOT NULL, signer_type TEXT NOT NULL DEFAULT 'individual', display_name TEXT NOT NULL DEFAULT '', organization_name TEXT NOT NULL DEFAULT '', contact_name TEXT NOT NULL DEFAULT '', affiliation TEXT NOT NULL DEFAULT '', role TEXT NOT NULL DEFAULT '', website TEXT NOT NULL DEFAULT '', public_statement TEXT NOT NULL DEFAULT '', email TEXT NOT NULL DEFAULT '', email_hash TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending_email', verification_token_hash TEXT, verification_expires_at TEXT, verified_at TEXT, management_token_hash TEXT, published_at TEXT, revoked_at TEXT, moderation_note TEXT NOT NULL DEFAULT '', duplicate_flags_json TEXT NOT NULL DEFAULT '[]', abuse_flags_json TEXT NOT NULL DEFAULT '[]', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS campaign_signature_rate_limits (key_hash TEXT PRIMARY KEY, attempts INTEGER NOT NULL DEFAULT 0, window_started_at TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE INDEX IF NOT EXISTS idx_campaign_signatures_campaign_status ON campaign_signatures(campaign_id,status,created_at DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_campaign_signatures_email_hash ON campaign_signatures(campaign_id,email_hash)`,
    `CREATE INDEX IF NOT EXISTS idx_campaign_signatures_verify ON campaign_signatures(verification_token_hash)`,
    `CREATE INDEX IF NOT EXISTS idx_campaign_signatures_manage ON campaign_signatures(management_token_hash)`]) await db.prepare(sql).run()
}
export async function getSignatureForm(db,campaignId){await ensureSignatureTables(db);const r=await db.prepare(`SELECT * FROM campaign_signature_forms WHERE campaign_id=?`).bind(campaignId).first();return r?{campaignId:r.campaign_id,enabled:Boolean(r.enabled),title:r.title,intro:r.intro,config:parse(r.config_json,{})}:null}
export async function saveSignatureForm(db,campaignId,input={}){await ensureSignatureTables(db);const config={allowIndividuals:input.config?.allowIndividuals!==false,allowOrganizations:input.config?.allowOrganizations!==false,showAffiliation:input.config?.showAffiliation!==false,allowStatement:input.config?.allowStatement!==false};await db.prepare(`INSERT INTO campaign_signature_forms(campaign_id,enabled,title,intro,config_json) VALUES(?,?,?,?,?) ON CONFLICT(campaign_id) DO UPDATE SET enabled=excluded.enabled,title=excluded.title,intro=excluded.intro,config_json=excluded.config_json,updated_at=CURRENT_TIMESTAMP`).bind(campaignId,input.enabled?1:0,clean(input.title||'Sign',180),clean(input.intro,1200),JSON.stringify(config)).run();return getSignatureForm(db,campaignId)}
export async function submitSignature(db,campaignId,input={},meta={}){await ensureSignatureTables(db);const form=await getSignatureForm(db,campaignId);if(!form?.enabled)throw http('Signing is not enabled for this campaign.',404);if(clean(input.company||input.website_confirm,200))return {suppressed:true};const signerType=input.signerType==='organization'?'organization':'individual';if(signerType==='individual'&&form.config.allowIndividuals===false)throw http('Individual signatures are disabled.',400);if(signerType==='organization'&&form.config.allowOrganizations===false)throw http('Organization signatures are disabled.',400);const email=String(input.email||'').trim().toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))throw http('Enter a valid email address.',400);const displayName=clean(input.displayName,180), organizationName=clean(input.organizationName,220), contactName=clean(input.contactName,180);if(signerType==='individual'&&!displayName)throw http('Display name is required.',400);if(signerType==='organization'&&(!organizationName||!contactName))throw http('Organization and contact name are required.',400);const emailHash=await sha(email);const rateKey=await sha(`${meta.rateSalt||'colophon'}:${meta.ip||''}:${campaignId}`);if(!(await consumeRate(db,rateKey)))throw http('Too many attempts. Try again later.',429);const prior=await db.prepare(`SELECT id,status FROM campaign_signatures WHERE campaign_id=? AND email_hash=? ORDER BY created_at DESC LIMIT 8`).bind(campaignId,emailHash).all();const duplicateFlags=(prior.results||[]).map(r=>`${r.status}:${r.id}`);const abuseFlags=[];if(duplicateFlags.length)abuseFlags.push('repeat_email');if(Number(input.formStartedAt)&&Date.now()-Number(input.formStartedAt)<2500)abuseFlags.push('fast_completion');const token=randomToken(), id=crypto.randomUUID(), expires=new Date(Date.now()+VERIFY_TTL).toISOString();await db.prepare(`INSERT INTO campaign_signatures(id,campaign_id,signer_type,display_name,organization_name,contact_name,affiliation,role,website,public_statement,email,email_hash,status,verification_token_hash,verification_expires_at,duplicate_flags_json,abuse_flags_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'pending_email',?,?,?,?)`).bind(id,campaignId,signerType,displayName,organizationName,contactName,clean(input.affiliation,220),clean(input.role,180),safeUrl(input.website),clean(input.publicStatement,1200),email,emailHash,await sha(token),expires,JSON.stringify(duplicateFlags),JSON.stringify(abuseFlags)).run();return{id,email,verificationToken:token,expiresAt:expires}}
export async function verifySignature(db,token){await ensureSignatureTables(db);const hash=await sha(token),row=await db.prepare(`SELECT * FROM campaign_signatures WHERE verification_token_hash=? AND status='pending_email' LIMIT 1`).bind(hash).first();if(!row||Date.parse(row.verification_expires_at||'')<=Date.now())throw http('Verification link is invalid or expired.',400);const manage=randomToken(),now=new Date().toISOString();const r=await db.prepare(`UPDATE campaign_signatures SET status='awaiting_moderation',verification_token_hash=NULL,verification_expires_at=NULL,verified_at=?,management_token_hash=?,updated_at=? WHERE id=? AND verification_token_hash=?`).bind(now,await sha(manage),now,row.id,hash).run();if(!Number(r?.meta?.changes||1))throw http('Verification link was already used.',400);return{item:privateRow({...row,status:'awaiting_moderation',verified_at:now},false),managementToken:manage}}
export async function prepareResend(db,id,campaignId){await ensureSignatureTables(db);const row=await db.prepare(`SELECT id,email,status FROM campaign_signatures WHERE id=? AND campaign_id=?`).bind(id,campaignId).first();if(!row||row.status!=='pending_email')throw http('Signature is not awaiting verification.',400);const token=randomToken(),expiresAt=new Date(Date.now()+VERIFY_TTL).toISOString();return{row,token,hash:await sha(token),expiresAt}}
export async function activateResend(db,id,campaignId,hash,expiresAt){const r=await db.prepare(`UPDATE campaign_signatures SET verification_token_hash=?,verification_expires_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND campaign_id=? AND status='pending_email'`).bind(hash,expiresAt,id,campaignId).run();if(!Number(r?.meta?.changes||1))throw http('Signature changed before replacement could be activated.',409)}
export async function listPublicSignatures(db,campaignId){await ensureSignatureTables(db);const r=await db.prepare(`SELECT id,signer_type,display_name,organization_name,affiliation,role,website,public_statement,published_at FROM campaign_signatures WHERE campaign_id=? AND status='approved' ORDER BY COALESCE(published_at,created_at) ASC`).bind(campaignId).all();const items=(r.results||[]).map(publicRow);return{items,counts:{total:items.length,individuals:items.filter(i=>i.signerType==='individual').length,organizations:items.filter(i=>i.signerType==='organization').length}}}
export async function listSignatureQueue(db,campaignId,status='all'){await ensureSignatureTables(db);const selected=STATUSES.includes(status)?status:'all';const q=selected==='all'?await db.prepare(`SELECT * FROM campaign_signatures WHERE campaign_id=? ORDER BY created_at DESC LIMIT 1000`).bind(campaignId).all():await db.prepare(`SELECT * FROM campaign_signatures WHERE campaign_id=? AND status=? ORDER BY created_at DESC LIMIT 1000`).bind(campaignId,selected).all();return(q.results||[]).map(r=>privateRow(r,true))}
export async function moderateSignature(db,id,action,note=''){const map={approve:'approved',reject:'rejected',spam:'spam',revoke:'revoked',remove:'revoked'};const status=map[action];if(!status)throw http('Unsupported moderation action.',400);const row=await db.prepare(`SELECT * FROM campaign_signatures WHERE id=?`).bind(id).first();if(!row)throw http('Signature not found.',404);if(status==='approved'&&row.status!=='awaiting_moderation'&&row.status!=='approved')throw http('Email verification is required before approval.',409);const now=new Date().toISOString();await db.prepare(`UPDATE campaign_signatures SET status=?,moderation_note=?,published_at=CASE WHEN ?='approved' THEN COALESCE(published_at,?) ELSE NULL END,revoked_at=CASE WHEN ?='revoked' THEN ? ELSE revoked_at END,updated_at=? WHERE id=?`).bind(status,clean(note,2000),status,now,status,now,now,id).run();return privateRow({...row,status,moderation_note:note,published_at:status==='approved'?(row.published_at||now):null},true)}
export async function bulkModerate(db,ids,action){const results=[];for(const id of [...new Set(ids.map(String))].slice(0,500)){try{results.push({id,ok:true,item:await moderateSignature(db,id,action)})}catch(e){results.push({id,ok:false,error:e.message})}}return results}
export async function getManagedSignature(db,token){await ensureSignatureTables(db);const row=await db.prepare(`SELECT * FROM campaign_signatures WHERE management_token_hash=? LIMIT 1`).bind(await sha(token)).first();if(!row)throw http('Management link is invalid.',404);return privateRow(row,false)}
export async function updateManagedSignature(db,token,patch={}){const hash=await sha(token),row=await db.prepare(`SELECT * FROM campaign_signatures WHERE management_token_hash=? LIMIT 1`).bind(hash).first();if(!row)throw http('Management link is invalid.',404);const revoke=patch.revoke===true||patch.hidden===true;const status=revoke?'revoked':row.status,now=new Date().toISOString();await db.prepare(`UPDATE campaign_signatures SET display_name=?,organization_name=?,affiliation=?,public_statement=?,status=?,published_at=CASE WHEN ?='revoked' THEN NULL ELSE published_at END,revoked_at=CASE WHEN ?='revoked' THEN ? ELSE revoked_at END,management_token_hash=CASE WHEN ?='revoked' THEN NULL ELSE management_token_hash END,updated_at=? WHERE id=? AND management_token_hash=?`).bind(patch.displayName===undefined?row.display_name:clean(patch.displayName,180),patch.organizationName===undefined?row.organization_name:clean(patch.organizationName,220),patch.affiliation===undefined?row.affiliation:clean(patch.affiliation,220),patch.publicStatement===undefined?row.public_statement:clean(patch.publicStatement,1200),status,status,status,now,status,now,row.id,hash).run();return privateRow({...row,status},false)}
export async function importLegacySignatures(db,campaignId,rows=[]){await ensureSignatureTables(db);let count=0;for(const row of rows.slice(0,5000)){const name=clean(row.name||row.organizationName,220);if(!name)continue;const id=`legacy-${campaignId}-${(await sha(`${name}:${row.location||''}`)).slice(0,20)}`;const type=row.signerType==='individual'?'individual':'organization';const now=new Date().toISOString();await db.prepare(`INSERT OR IGNORE INTO campaign_signatures(id,campaign_id,signer_type,display_name,organization_name,affiliation,website,public_statement,email_hash,status,verified_at,published_at) VALUES(?,?,?,?,?,?,?,?,?,'approved',?,?)`).bind(id,campaignId,type,type==='individual'?name:'',type==='organization'?name:'',clean(row.location,220),safeUrl(row.url),clean(row.statement,1200),await sha(`legacy:${id}`),now,now).run();count++}return count}
export async function exportSignatureCsv(db,campaignId){const rows=await listSignatureQueue(db,campaignId,'all');const cols=['id','signerType','displayName','organizationName','affiliation','role','website','publicStatement','email','status','verifiedAt','publishedAt','createdAt'];return [cols.join(','),...rows.map(r=>cols.map(c=>csv(r[c])).join(','))].join('\n')}
function publicRow(r){return{id:r.id,signerType:r.signer_type,displayName:r.display_name,organizationName:r.organization_name,affiliation:r.affiliation,role:r.role,website:r.website,publicStatement:r.public_statement,publishedAt:r.published_at}}
function privateRow(r,email=true){return{...publicRow(r),campaignId:r.campaign_id,contactName:r.contact_name,email:email?r.email:undefined,status:r.status,verifiedAt:r.verified_at,revokedAt:r.revoked_at,moderationNote:r.moderation_note,duplicateFlags:parse(r.duplicate_flags_json,[]),abuseFlags:parse(r.abuse_flags_json,[]),createdAt:r.created_at,updatedAt:r.updated_at}}
async function consumeRate(db,key){const now=new Date(),row=await db.prepare(`SELECT attempts,window_started_at FROM campaign_signature_rate_limits WHERE key_hash=?`).bind(key).first();if(!row||Date.now()-Date.parse(row.window_started_at)>3600000){await db.prepare(`INSERT INTO campaign_signature_rate_limits(key_hash,attempts,window_started_at) VALUES(?,1,?) ON CONFLICT(key_hash) DO UPDATE SET attempts=1,window_started_at=excluded.window_started_at,updated_at=CURRENT_TIMESTAMP`).bind(key,now.toISOString()).run();return true}if(Number(row.attempts)>=8)return false;await db.prepare(`UPDATE campaign_signature_rate_limits SET attempts=attempts+1,updated_at=CURRENT_TIMESTAMP WHERE key_hash=?`).bind(key).run();return true}
function randomToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function sha(v){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v||'')));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function clean(v,n){return String(v||'').trim().slice(0,n)} function parse(v,f){try{return JSON.parse(v)}catch{return f}} function safeUrl(v){try{const u=new URL(String(v||''));return ['http:','https:'].includes(u.protocol)?u.toString():''}catch{return''}} function http(msg,status){return Object.assign(new Error(msg),{status})} function csv(v){return `"${String(v??'').replaceAll('"','""')}"`}
