import { normalizeCourse, publicCourse } from '../../../shared/courseModel.js'
export async function ensureCourseTables(db){
  await db.prepare(`CREATE TABLE IF NOT EXISTS courses (id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT 'draft', revision INTEGER NOT NULL DEFAULT 0, content_json TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()
  await db.prepare(`CREATE TABLE IF NOT EXISTS course_publications (course_id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, version INTEGER NOT NULL DEFAULT 1, content_json TEXT NOT NULL, published_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()
  await db.prepare(`CREATE TABLE IF NOT EXISTS course_revisions (id TEXT PRIMARY KEY, course_id TEXT NOT NULL, revision INTEGER NOT NULL, status TEXT NOT NULL, content_json TEXT NOT NULL, actor TEXT NOT NULL DEFAULT 'editor', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()
  await db.prepare(`CREATE INDEX IF NOT EXISTS idx_courses_status ON courses(status, updated_at DESC)`).run()
  await db.prepare(`CREATE INDEX IF NOT EXISTS idx_course_revisions_course ON course_revisions(course_id, revision DESC)`).run()
}
export async function listCourses(db,{publicOnly=false}={}){ await ensureCourseTables(db); if(publicOnly){ const r=await db.prepare(`SELECT content_json FROM course_publications ORDER BY published_at DESC`).all(); return (r.results||[]).map(r=>JSON.parse(r.content_json)).filter(Boolean) } const r=await db.prepare(`SELECT content_json FROM courses ORDER BY updated_at DESC`).all(); return (r.results||[]).map(r=>normalizeCourse(JSON.parse(r.content_json))) }
export async function getCourse(db,key,{editor=false}={}){ await ensureCourseTables(db); const raw=String(key||'').trim(); if(!raw)return null; if(editor){ const row=await db.prepare(`SELECT content_json FROM courses WHERE id=? OR slug=? LIMIT 1`).bind(raw,raw).first(); return row?.content_json?normalizeCourse(JSON.parse(row.content_json)):null } const row=await db.prepare(`SELECT content_json FROM course_publications WHERE course_id=? OR slug=? LIMIT 1`).bind(raw,raw).first(); return row?.content_json?JSON.parse(row.content_json):null }
export async function saveCourse(db,input,actor='editor'){ await ensureCourseTables(db); const incoming=normalizeCourse(input); const current=await db.prepare(`SELECT content_json, revision, created_at FROM courses WHERE id=? OR slug=? LIMIT 1`).bind(incoming.id,incoming.slug).first(); const expected=Number(input.revision||0); const actual=Number(current?.revision||0); if(current && expected!==actual) throw Object.assign(new Error('Course changed since it was loaded. Reload before saving.'),{status:409}); const next=normalizeCourse({...incoming,revision:actual+1,createdAt:current?.created_at||incoming.createdAt,updatedAt:new Date().toISOString()}); const previous=current?.content_json?normalizeCourse(JSON.parse(current.content_json)):null; const statements=[]; if(previous) statements.push(db.prepare(`INSERT INTO course_revisions(id,course_id,revision,status,content_json,actor) VALUES(?,?,?,?,?,?)`).bind(crypto.randomUUID(),previous.id,actual,previous.status,JSON.stringify(previous),actor)); statements.push(db.prepare(`INSERT INTO courses(id,slug,status,revision,content_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug,status=excluded.status,revision=excluded.revision,content_json=excluded.content_json,updated_at=excluded.updated_at`).bind(next.id,next.slug,next.status,next.revision,JSON.stringify(next),next.createdAt,next.updatedAt)); if(next.status==='published'){ const published=publicCourse({...next,publishedVersion:(Number(previous?.publishedVersion||0)+1),publishedAt:new Date().toISOString()}); next.publishedVersion=published.publishedVersion; next.publishedAt=published.publishedAt; statements[statements.length-1]=db.prepare(`INSERT INTO courses(id,slug,status,revision,content_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug,status=excluded.status,revision=excluded.revision,content_json=excluded.content_json,updated_at=excluded.updated_at`).bind(next.id,next.slug,next.status,next.revision,JSON.stringify(next),next.createdAt,next.updatedAt); statements.push(db.prepare(`INSERT INTO course_publications(course_id,slug,version,content_json,published_at) VALUES(?,?,?,?,?) ON CONFLICT(course_id) DO UPDATE SET slug=excluded.slug,version=excluded.version,content_json=excluded.content_json,published_at=excluded.published_at`).bind(next.id,next.slug,published.publishedVersion,JSON.stringify(published),published.publishedAt)); } else if(next.status==='archived') statements.push(db.prepare(`DELETE FROM course_publications WHERE course_id=?`).bind(next.id)); await db.batch(statements); return next }
export async function deleteCourse(db,id){ await ensureCourseTables(db); await db.batch([db.prepare(`DELETE FROM course_publications WHERE course_id=?`).bind(id),db.prepare(`DELETE FROM course_revisions WHERE course_id=?`).bind(id),db.prepare(`DELETE FROM courses WHERE id=?`).bind(id)]); return true }
